In [1]:
import pandas as pd


In [2]:
import numpy as np
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

In [3]:
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
b.ndim

2

In [5]:
b.shape

(2, 3)

In [6]:
b.dtype

dtype('float64')

In [7]:
b.itemsize

8

In [8]:
b.itemsize

8

In [9]:
b.size

6

In [10]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
a[1, 5]

13

In [12]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
a[: ,2]

array([ 3, 10])

In [14]:
a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
a[1,5] = 20
a[:,2] = [1,2]

In [16]:
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [17]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
b[0,1,1]

4

In [19]:
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((4,3,2), dtype = 'int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [22]:
np.full((2,2),98)

array([[98, 98],
       [98, 98]])

In [23]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [24]:
np.random.rand(7)

array([0.690521  , 0.96210501, 0.52870381, 0.26399346, 0.74952667,
       0.02263134, 0.17779482])

In [25]:
np.random.randint(7)

6

In [26]:
np.random.rand(4,3)

array([[0.03566227, 0.6502839 , 0.64019731],
       [0.46240516, 0.17362338, 0.4873282 ],
       [0.57478985, 0.39458681, 0.37114413],
       [0.21923236, 0.77784399, 0.29904523]])

In [27]:
np.random.randint(1,9, size=(4,4))

array([[6, 4, 1, 6],
       [6, 4, 4, 2],
       [2, 1, 6, 2],
       [4, 6, 1, 6]])

In [28]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
arr = np.array([[1,2,3]])
r = np.repeat(arr,3, axis =0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [30]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
z= np.zeros((3,3))
print(z)
output[1:-1,1:-1] = z
print(output)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [33]:
arr = np.array([1,2,3])
r = np.repeat(arr,3, axis =0)
print(r)

[1 1 1 2 2 2 3 3 3]


In [34]:
a = np.array([1,2,3,4,5])

In [35]:
print(a)

[1 2 3 4 5]


In [36]:
a - 2

array([-1,  0,  1,  2,  3])

In [37]:
a - 0

array([1, 2, 3, 4, 5])

In [38]:
a - 1

array([0, 1, 2, 3, 4])

In [39]:
a*10

array([10, 20, 30, 40, 50])

In [40]:
print(a)

[1 2 3 4 5]


In [41]:
b = np.array([9,8,7,6,7])
a+b

array([10, 10, 10, 10, 12])

In [42]:
a ** 3

array([  1,   8,  27,  64, 125])

In [43]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [44]:
print(a)


[1 2 3 4 5]


In [45]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

c = np.matmul(a,b)
c

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [46]:
np.linalg.det(c)

0.0

In [47]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.min(stats)

1

In [49]:
np.max(stats)

6

In [50]:
np.max(stats,axis =1)

array([3, 6])

In [51]:
np.sum(stats)

21

In [52]:
np.sum(stats,axis = 0)

array([5, 7, 9])

In [53]:
np.sum(stats,axis=1)

array([ 6, 15])

In [54]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(4,2)
after

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [56]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])

np.vstack([v1,v2,v1,v2])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [57]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])

np.hstack([v1,v2,v1,v2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

In [58]:
filedata = np.genfromtxt('data.txt',delimiter=',')

In [59]:
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [60]:
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [61]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [62]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])